### ISSUE TITLE
JS error on usage

### ISSUE THREAD

**Issue by bfosberry** [usermindinc/hubot-github-pr-reporter#5]
```
"dependencies": {
    "hubot": "^2.18.0",
    "hubot-diagnostics": "0.0.1",
    "hubot-github-pr-reporter": "^1.1.1",
    "hubot-google-images": "^0.1.0",
    "hubot-google-translate": "^0.1.0",
    "hubot-help": "^0.1.1",
    "hubot-heroku-keepalive": "0.0.4",
    "hubot-maps": "0.0.0",
    "hubot-pager-me": "^2.0.2",
    "hubot-pugme": "^0.1.0",
    "hubot-redis-brain": "0.0.2",
    "hubot-remind-her": "^0.4.1",
    "hubot-rules": "^0.1.0",
    "hubot-scripts": "^2.5.16",
    "hubot-shipit": "^0.1.1",
    "hubot-slack": "git://github.com/slackhq/hubot-slack.git#1156fd6",
    "hubot-youtube": "^0.1.2"
  },
  "engines": {
    "node": "0.10.x"
  }
```

```
2016-02-12T15:32:37.252192+00:00 app[web.1]:   at parseDigestRequest (/app/node_modules/hubot-github-pr-reporter/src/github-pr-reporter.coffee:364:5, <js>:389:21)
2016-02-12T15:32:37.252188+00:00 app[web.1]: [Fri Feb 12 2016 15:32:37 GMT+0000 (UTC)] ERROR ReferenceError: Promise is not defined
2016-02-12T15:32:37.252194+00:00 app[web.1]:   at TextListener.callback (/app/node_modules/hubot-github-pr-reporter/src/github-pr-reporter.coffee:407:5, <js>:435:14)
2016-02-12T15:32:37.252195+00:00 app[web.1]:   at executeListener (/app/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
2016-02-12T15:32:37.252196+00:00 app[web.1]:   at allDone (/app/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
2016-02-12T15:32:37.252197+00:00 app[web.1]:   at /app/node_modules/hubot/node_modules/async/lib/async.js:274:13
2016-02-12T15:32:37.252198+00:00 app[web.1]:   at Object.async.eachSeries (/app/node_modules/hubot/node_modules/async/lib/async.js:142:20)
2016-02-12T15:32:37.252198+00:00 app[web.1]:   at Object.async.reduce (/app/node_modules/hubot/node_modules/async/lib/async.js:268:15)
2016-02-12T15:32:37.252199+00:00 app[web.1]:   at /app/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
2016-02-12T15:32:37.252201+00:00 app[web.1]: 
2016-02-12T15:32:37.252200+00:00 app[web.1]:   at process._tickCallback (node.js:448:13)
```

Could be related to a css-loader issue: https://github.com/webpack/css-loader/issues/145

Any ideas?

**Comment by downie** [comment]
I think the [Promises import](https://github.com/usermindinc/hubot-github-pr-reporter/pull/6) you added fixed this. It only worked before if it was running in a later version of node with native Promises support.

**Comment by bfosberry** [comment]
Thanks!
