### ISSUE TITLE
Unable to get integration working - 404 errors, TypeError

### ISSUE THREAD

**Issue by bfosberry** [usermindinc/hubot-github-pr-reporter#9]
Using a token with the following scopes: user, notifications, repo:status

```
Hubot> hubot show prs org:myorg
Hubot> [Tue Mar 01 2016 12:11:45 GMT-0600 (CST)] ERROR TypeError: Object [object Object],[object Object],[object Object],[object Object],[object Object] has no method 'find'
  at parseDigestRequest (/home/bfosberry/workspace/captain/node_modules/hubot-github-pr-reporter/src/github-pr-reporter.coffee:282:5, <js>:288:44)
  at TextListener.callback (/home/bfosberry/workspace/captain/node_modules/hubot-github-pr-reporter/src/github-pr-reporter.coffee:408:5, <js>:437:14)
  at executeListener (/home/bfosberry/workspace/captain/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/home/bfosberry/workspace/captain/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /home/bfosberry/workspace/captain/node_modules/hubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/home/bfosberry/workspace/captain/node_modules/hubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/home/bfosberry/workspace/captain/node_modules/hubot/node_modules/async/lib/async.js:268:15)
  at /home/bfosberry/workspace/captain/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at process._tickCallback (node.js:415:13)

Hubot> hubot show prs user:bfosberry
Hubot> 
Hubot> hubot show prs 
Hubot> [Tue Mar 01 2016 12:12:14 GMT-0600 (CST)] ERROR 404 Not Found
[Tue Mar 01 2016 12:12:14 GMT-0600 (CST)] ERROR 404 Not Found
[Tue Mar 01 2016 12:12:14 GMT-0600 (CST)] ERROR 404 Not Found
[Tue Mar 01 2016 12:12:14 GMT-0600 (CST)] ERROR 404 Not Found
[Tue Mar 01 2016 12:12:14 GMT-0600 (CST)] ERROR 404 Not Found
```

**Comment by bfosberry** [comment]
So if I use a token with the org:read scope, non user/org specific "show prs" commands work. Otherwise I get either a blank response, or I get the type error

**Comment by bfosberry** [comment]
I think a related issue is being unable to unsubscribe from notifications:

```
2016-03-01T18:44:30.351416+00:00 app[web.1]: [Tue Mar 01 2016 18:44:30 GMT+0000 (UTC)] ERROR TypeError: Object [object Object] has no method 'findIndex'
2016-03-01T18:44:30.351454+00:00 app[web.1]:   at TextListener.callback (/app/node_modules/hubot-github-pr-reporter/src/github-pr-reporter.coffee:464:7, <js>:511:39)
2016-03-01T18:44:30.351457+00:00 app[web.1]:   at executeListener (/app/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
2016-03-01T18:44:30.351459+00:00 app[web.1]:   at allDone (/app/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
2016-03-01T18:44:30.351460+00:00 app[web.1]:   at /app/node_modules/hubot/node_modules/async/lib/async.js:274:13
2016-03-01T18:44:30.351460+00:00 app[web.1]:   at Object.async.eachSeries (/app/node_modules/hubot/node_modules/async/lib/async.js:142:20)
2016-03-01T18:44:30.351461+00:00 app[web.1]:   at Object.async.reduce (/app/node_modules/hubot/node_modules/async/lib/async.js:268:15)
2016-03-01T18:44:30.351462+00:00 app[web.1]:   at /app/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
2016-03-01T18:44:30.351463+00:00 app[web.1]:   at process._tickCallback (node.js:448:13)
2016-03-01T18:44:30.351464+00:00 app[web.1]: 
```

**Comment by bfosberry** [comment]
ping @downie any ideas?

**Comment by downie** [comment]
Nothing jumps out at me. I'll take a look later this afternoon/tonight and let you know what I find.

**Comment by bfosberry** [comment]
Thanks! It almost seems like it's a different github api version. Would my package file assist debugging?

**Comment by downie** [comment]
yeah, that would be great! It'll give me more runway to debug if it's one of those "it works on my box" kind of bugs.

**Comment by bfosberry** [comment]
```
{
  "name": "hubot",
  "version": "0.0.0",
  "private": true,
  "author": "mr author",
  "description": "doing stuff",
  "dependencies": {
    "hubot": "^2.18.0",
    "hubot-diagnostics": "0.0.1",
    "hubot-github-pr-reporter": "^1.1.2",
    "hubot-google-images": "^0.1.0",
    "hubot-google-translate": "^0.1.0",
    "hubot-help": "^0.1.1",
    "hubot-heroku-keepalive": "0.0.4",
    "hubot-maps": "0.0.0",
    "hubot-pager-me": "^2.0.2",
    "hubot-pugme": "^0.1.0",
    "hubot-redis-brain": "0.0.2",
    "hubot-remind-her": "^0.4.1",
    "hubot-rules": "^0.1.0",
    "hubot-scripts": "^2.5.16",
    "hubot-shipit": "^0.1.1",
    "hubot-slack": "git://github.com/slackhq/hubot-slack.git#1156fd6",
    "hubot-youtube": "^0.1.2",
    "promise": "^7.1.1"
  },
  "engines": {
    "node": "0.10.x"
  }
}
```

**Comment by downie** [comment]
I was playing with this for a while. I fixed some dependency issues, but I don't think that's the problem you're seeing.

What version of node are you using? Those errors appear to be referring to my [find](https://github.com/usermindinc/hubot-github-pr-reporter/blob/master/src/github-pr-reporter.coffee#L282) and [findIndex](https://github.com/usermindinc/hubot-github-pr-reporter/blob/master/src/github-pr-reporter.coffee#L464) calls, which should be properly supported by node.

**Comment by bfosberry** [comment]
Im using 0.10.25, trying to track down what our prod app is using as well

**Comment by bfosberry** [comment]
A coworker told me that is WAY out of date, with 5.6.0 it works perfectly

**Comment by downie** [comment]
Cool. I'll consider this fixed then.
